name: main-merged
on:
  push:
    branches:
      - main
permissions:
  contents: write
  issues: write
  pull-requests: write
env:
  DEV_ACCOUNT: 545685513152
  SHARED_ACCOUNT: 500487477676
  REGION: us-east-1
  S3_ARTIFACT_BUCKET: artifacts-500487477676-us-east-1
jobs:
    version:
        runs-on: ubuntu-latest
        name: version 
        steps:
          - name: Call Versioning
            uses: KeyShare-Platform/Github-Actions/Versioning@main
